#!/usr/bin/env python3
"""Create capped-400 real-data pairs for the classical/LLM fair comparison.

The generated datasets keep all rows from regimes with <= 400 observations and
sample exactly 400 rows from larger regimes. Sampling is deterministic.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "DATA" / "custom_pairs"
PAIRMETA_PATH = ROOT / "DATA" / "pairmeta_with_ground_truth.txt"
CAP = 400
SEED = 42

BLOCK_START = "# BEGIN GENERATED capped_400 pairmeta entries"
BLOCK_END = "# END GENERATED capped_400 pairmeta entries"


@dataclass(frozen=True)
class PairMeta:
    dataset: str
    cause_cols: str
    effect_cols: str
    weight: str
    threshold_var: str
    threshold_val: str
    low_dir: str
    high_dir: str

    @classmethod
    def parse(cls, line: str) -> "PairMeta":
        parts = [part.strip() for part in line.rstrip("\n").split("|")]
        if len(parts) != 8:
            raise ValueError(f"Malformed pairmeta line: {line!r}")
        return cls(*parts)

    def with_dataset(self, dataset: str) -> "PairMeta":
        return PairMeta(
            dataset=dataset,
            cause_cols=self.cause_cols,
            effect_cols=self.effect_cols,
            weight=self.weight,
            threshold_var=self.threshold_var,
            threshold_val=self.threshold_val,
            low_dir=self.low_dir,
            high_dir=self.high_dir,
        )

    def to_line(self) -> str:
        return "|".join(
            [
                self.dataset,
                self.cause_cols,
                self.effect_cols,
                self.weight,
                self.threshold_var,
                self.threshold_val,
                self.low_dir,
                self.high_dir,
            ]
        )


SOURCE_DATASETS = [
    "dfp_glucose",
    "wind_ozone",
    "hk_ozone_temperature",
    "emissions_total_per_capita_renewable_share_of_electricity__pct",
    "swc_latent_heat_flux",
    "interest_inflation",
    "debt_growth",
    "fertilizer_crop_amount",
    "co2_energy",
    "fertility_hdi",
    "vienna_soil_moisture_evapotranspiration",
    "bee_traffic_weight_change",
]


def read_pairmeta() -> dict[str, PairMeta]:
    pairmeta: dict[str, PairMeta] = {}
    for line in PAIRMETA_PATH.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        meta = PairMeta.parse(stripped)
        pairmeta[meta.dataset] = meta
    return pairmeta


def resolve_threshold_column(df: pd.DataFrame, threshold_var: str) -> str:
    for col in df.columns:
        if threshold_var.lower() in col.lower() or col.lower() in threshold_var.lower():
            return col

    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    if not numeric_cols:
        raise ValueError(f"No numeric columns available for threshold {threshold_var!r}")
    return numeric_cols[0]


def sample_regime(df: pd.DataFrame, size: int, seed: int) -> pd.DataFrame:
    if len(df) <= size:
        return df.copy()
    return df.sample(n=size, random_state=seed).sort_index()


def create_capped_dataset(dataset: str, meta: PairMeta) -> tuple[str, int, int]:
    source_path = DATA_DIR / f"{dataset}.txt"
    if not source_path.exists():
        raise FileNotFoundError(source_path)

    df = pd.read_csv(source_path, sep=r"\s+", header=0, engine="python")
    threshold_col = resolve_threshold_column(df, meta.threshold_var)
    threshold_val = float(meta.threshold_val)

    low = df[df[threshold_col] <= threshold_val]
    high = df[df[threshold_col] > threshold_val]

    capped_low = sample_regime(low, CAP, SEED)
    capped_high = sample_regime(high, CAP, SEED + 1)
    capped = pd.concat([capped_low, capped_high], axis=0).reset_index(drop=True)

    capped_name = f"capped_400_{dataset}"
    output_path = DATA_DIR / f"{capped_name}.txt"
    capped.to_csv(output_path, sep="\t", index=False)

    return capped_name, len(capped_low), len(capped_high)


def replace_generated_pairmeta_block(entries: list[PairMeta]) -> None:
    original_lines = PAIRMETA_PATH.read_text(encoding="utf-8").splitlines()
    new_lines: list[str] = []
    in_generated_block = False

    for line in original_lines:
        if line.strip() == BLOCK_START:
            in_generated_block = True
            continue
        if line.strip() == BLOCK_END:
            in_generated_block = False
            continue
        if not in_generated_block:
            new_lines.append(line)

    block = [
        "",
        BLOCK_START,
        f"# Generated by scripts/create_capped_400_datapairs.py with seed={SEED}, max {CAP} rows per regime.",
    ]
    block.extend(entry.to_line() for entry in entries)
    block.append(BLOCK_END)

    insert_at = len(new_lines)
    for idx, line in enumerate(new_lines):
        if line.startswith("# -----------------------------------------------------------------------------"):
            insert_at = idx
            break

    updated_lines = new_lines[:insert_at] + block + new_lines[insert_at:]
    PAIRMETA_PATH.write_text("\n".join(updated_lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    pairmeta = read_pairmeta()
    generated_entries: list[PairMeta] = []

    print(f"Creating capped datasets in {DATA_DIR}")
    for dataset in SOURCE_DATASETS:
        if dataset not in pairmeta:
            raise KeyError(f"Missing pairmeta entry for {dataset}")

        capped_name, low_n, high_n = create_capped_dataset(dataset, pairmeta[dataset])
        generated_entries.append(pairmeta[dataset].with_dataset(capped_name))
        print(f"{capped_name}: {low_n} / {high_n}")

    replace_generated_pairmeta_block(generated_entries)
    print(f"Updated {PAIRMETA_PATH}")


if __name__ == "__main__":
    main()
